#!/bin/bash

# Slackware build script for qt6-slackbuilds-generator

# Copyright 2025 Antonio Leal, Porto Salvo, Oeiras, Portugal
# All rights reserved.
#
# Redistribution and use of this script, with or without modification, is
# permitted provided that the following conditions are met:
#
# 1. Redistributions of this script must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#
#  THIS SOFTWARE IS PROVIDED BY THE AUTHOR "AS IS" AND ANY EXPRESS OR IMPLIED
#  WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
#  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO
#  EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
#  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
#  PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
#  OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
#  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
#  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
#  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.


# Setup
VERSION=6.10.1 # The Qt version you want, for example 6.10.1
MAINVERSION=$(echo $VERSION | cut -d"." -f 1,2)  # Holds "6.10", for example

# Execution
cd $(dirname $0) ; CWD=$(pwd)

# Download Qt submodules (except qtbase, of course)
rm -rf downloads
mkdir -p downloads
cd downloads
for NAME in $(cat $CWD/basenames.dat)
do
    URL="https://download.qt.io/archive/qt/$MAINVERSION/$VERSION/submodules/qt$NAME-everywhere-src-$VERSION.tar.xz"
    wget $URL
done
