#!/bin/bash

# Slackware build script for qt6-slackbuilds-generator

# Copyright 2025 Antonio Leal, Porto Salvo, Oeiras, Portugal
# All rights reserved.
#
# Redistribution and use of this script, with or without modification, is
# permitted provided that the following conditions are met:
#
# 1. Redistributions of this script must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#
#  THIS SOFTWARE IS PROVIDED BY THE AUTHOR "AS IS" AND ANY EXPRESS OR IMPLIED
#  WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
#  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO
#  EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
#  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
#  PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
#  OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
#  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
#  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
#  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.


# Setup
VERSION=6.10.1 # The Qt version you want, for example 6.10.1
MAINVERSION=$(echo $VERSION | cut -d"." -f 1,2)  # Holds "6.10", for example
SOLUTION="qt6-prebuilt_environment qt6-base qt6-shadertools qt6-svg qt6-imageformats qt6-languageserver qt6-declarative qt6-serialport qt6-websockets qt6-networkauth qt6-activeqt qt6-tools qt6-5compat qt6-scxml qt6-connectivity qt6-httpserver qt6-positioning qt6-webchannel qt6-webengine qt6-webview qt6-serialbus qt6-quicktimeline qt6-quick3d qt6-multimedia qt6-charts qt6-3d qt6-grpc qt6-remoteobjects qt6-sensors qt6-datavis3d qt6-graphs qt6-quick3dphysics qt6-quickeffectmaker qt6-location qt6-lottie qt6-speech qt6-wayland qt6-translations qt6-virtualkeyboard qt6-doc"

# Execution
cd $(dirname $0) ; CWD=$(pwd)
echo
echo "Generating Qt $VERSION SlackBuilds into the 'output' directory:"
echo
rm -rf output
mkdir -p output
cd output

for NAME in $SOLUTION
do
    echo "$NAME"
    if [[ "$NAME" == "qt6-prebuilt_environment" ]]; then
        cp -axu ../qt6-prebuilt_environment .
        cp ../downloads/libclang-llvmorg-20.1.0-linux-Rhel8.10-gcc10.0-x86_64.7z qt6-prebuilt_environment
        continue
    fi
    if [[ "$NAME" == "qt6-base" ]]; then
        cp -axu ../qt6-base .
        cp ../downloads/qtbase-everywhere-src-$VERSION.tar.xz qt6-base
        continue
    fi
    TARBALL="qt${NAME:4}-everywhere-src-$VERSION.tar.xz"
    MD5=`md5sum $CWD/downloads/$TARBALL | cut -d' ' -f1`

    # Now read the dependencies
    DEPENDENCIES=""
    for d in $(tar --to-command=cat -xf $CWD/downloads/qt${NAME:4}-everywhere-src-$VERSION.tar.xz qt${NAME:4}-everywhere-src-$VERSION/dependencies.yaml | grep "qt" | awk '{print substr($0,6,length($0)-6)}')
    do
        DEPENDENCIES="$DEPENDENCIES qt6-${d:2}"
    done

    # Create the output slackbuild directory
    rm -rf $CWD/output/$NAME
    mkdir -p $CWD/output/$NAME
    cd $CWD/output/$NAME

    # Build README
    sed -e "s/_prgnam_/${NAME:4}/g" \
        $CWD/template/README > $CWD/output/$NAME/README

    # Build slack-desc
    sed -e "s/_prgnam_/${NAME:4}/g" \
        -e "s/_ruler_/`echo ${NAME:4} | tr "[:alnum:]" " "`/g" \
        $CWD/template/slack-desc > $CWD/output/$NAME/slack-desc

    # Build info
    sed -e "s/_prgnam_/${NAME:4}/g" \
        -e "s/_version_/$VERSION/g" \
        -e "s/_mainversion_/$MAINVERSION/g" \
        -e "s/_md5_/$MD5/g" \
        -e "s/_dependencies_/${DEPENDENCIES}/g" \
        $CWD/template/info > $CWD/output/$NAME/$NAME.info

    # Build SlackBuild
    sed -e "s/_prgnam_/${NAME:4}/g" \
        -e "s/_version_/$VERSION/g" \
        $CWD/template/SlackBuild > $CWD/output/$NAME/$NAME.SlackBuild

    # Copy TARBALL to SlackBuild directory
    cp $CWD/downloads/$TARBALL .
done

echo
echo "Done."
